### ISSUE TITLE
Unable to go fullscreen on iPhoneX running on IOS13

### ISSUE THREAD

**Issue by joseph118** [flocasts/flo-angular#227]
Importing the `FloFullscreenModule` and trying to go fullscreen on IOS 13.1.3 doesn't seem to work

**Comment by patrickmichalina** [comment]
Confirming it happens on this demo page?

https://flosports-component-library.herokuapp.com/fullscreen

**Comment by patrickmichalina** [comment]
I tested in 13.3 and it works but don’t have a device with that exact version to test with

**Comment by joseph118** [comment]
Testing on iPhone X running on iOS 13.3
![IMG_20191213_160553](https://user-images.githubusercontent.com/6863655/70809716-abb75080-1dc2-11ea-8c5c-31ab2663c7f7.jpg)

It seems that the fullscreen on the video player works (3rd fullscreen), but the buttons related with 1st and 2nd container doesn't. Infact, the buttons are not visible on the iPhone screen

**Comment by patrickmichalina** [comment]
Those two buttons won’t show on iOS since it does not support the fullscreen API. the third button is special and shows because it’s attached to a video element which does have a fullscreen event it can fire.

**Comment by patrickmichalina** [comment]
I haven’t documented these subtleties so understandably confusing.

**Comment by joseph118** [comment]
Sorry for the lack of information from my end, I wasn't yet sure what the problem was considering it worked on all devices including iPad.

Thank you for pointing out the problem :)

**Comment by patrickmichalina** [comment]
I think another thing to consider is to DISABLE the buttons instead of removing them from the DOM like the current directives do. That’s a feature I’ve been thinking about lately.
